window.mt = window.mt || {}; window.mt.data = {
  "assets": {
    "name": "assets",
    "contents": [
      {
        "name": "Loading",
        "contents": [
          {
            "id": 1,
            "name": "preload.png",
            "fullPath": "/Loading/preload.png",
            "key": "/loading.png",
            "width": 190,
            "height": 9,
            "frameWidth": 190,
            "frameHeight": 9,
            "frameMax": -1,
            "margin": 0,
            "spacing": 0,
            "anchorX": 0,
            "anchorY": 0,
            "fps": 10,
            "updated": 1406817915033,
            "atlas": ""
          },
          {
            "id": 2,
            "name": "loading.png",
            "fullPath": "/Loading/loading.png",
            "key": "/preload.png",
            "width": 190,
            "height": 9,
            "frameWidth": 190,
            "frameHeight": 9,
            "frameMax": -1,
            "margin": 0,
            "spacing": 0,
            "anchorX": 0,
            "anchorY": 0,
            "fps": 10,
            "updated": 1406817917030,
            "atlas": ""
          }
        ],
        "count": 0,
        "id": 4,
        "fullPath": "/Loading",
        "isClosed": true
      },
      {
        "id": 19,
        "name": "background_city.png",
        "fullPath": "/background_city.png",
        "key": "/background_city.png",
        "width": 640,
        "height": 188,
        "frameWidth": 640,
        "frameHeight": 188,
        "frameMax": -1,
        "margin": 0,
        "spacing": 0,
        "anchorX": 0,
        "anchorY": 0,
        "fps": 10,
        "updated": 1409232725582,
        "atlas": ""
      },
      {
        "id": 20,
        "name": "background_grass.png",
        "fullPath": "/background_grass.png",
        "key": "/background_grass.png",
        "width": 640,
        "height": 47,
        "frameWidth": 640,
        "frameHeight": 47,
        "frameMax": -1,
        "margin": 0,
        "spacing": 0,
        "anchorX": 0,
        "anchorY": 0,
        "fps": 10,
        "updated": 1409232725584,
        "atlas": ""
      },
      {
        "id": 24,
        "name": "background_hill1.png",
        "fullPath": "/background_hill1.png",
        "key": "/background_hill1.png",
        "width": 640,
        "height": 85,
        "frameWidth": 640,
        "frameHeight": 85,
        "frameMax": -1,
        "margin": 0,
        "spacing": 0,
        "anchorX": 0,
        "anchorY": 0,
        "fps": 10,
        "updated": 1409233528731,
        "atlas": ""
      },
      {
        "id": 22,
        "name": "background_hill2.png",
        "fullPath": "/background_hill2.png",
        "key": "/background_hill2.png",
        "width": 640,
        "height": 99,
        "frameWidth": 640,
        "frameHeight": 99,
        "frameMax": -1,
        "margin": 0,
        "spacing": 0,
        "anchorX": 0,
        "anchorY": 0,
        "fps": 10,
        "updated": 1409232725585,
        "atlas": ""
      },
      {
        "id": 23,
        "name": "background_sky.png",
        "fullPath": "/background_sky.png",
        "key": "/background_sky.png",
        "width": 640,
        "height": 320,
        "frameWidth": 640,
        "frameHeight": 320,
        "frameMax": -1,
        "margin": 0,
        "spacing": 0,
        "anchorX": 0,
        "anchorY": 0,
        "fps": 10,
        "updated": 1409232725585,
        "atlas": ""
      },
      {
        "id": 7,
        "name": "character.png",
        "fullPath": "/character.png",
        "key": "/character.png",
        "width": 360,
        "height": 540,
        "frameWidth": 90,
        "frameHeight": 90,
        "frameMax": -1,
        "margin": 0,
        "spacing": 0,
        "anchorX": 0.5,
        "anchorY": 0.5,
        "fps": 10,
        "updated": 1409224167416,
        "atlas": "",
        "physics": {
          "enable": 0
        },
        "userData": {}
      },
      {
        "id": 14,
        "name": "gold.png",
        "fullPath": "/gold.png",
        "key": "/gold.png",
        "width": 64,
        "height": 64,
        "frameWidth": 64,
        "frameHeight": 64,
        "frameMax": -1,
        "margin": 0,
        "spacing": 0,
        "anchorX": 0,
        "anchorY": 0,
        "fps": 10,
        "updated": 1409224247322,
        "atlas": "",
        "physics": {
          "enable": 0
        },
        "userData": {}
      },
      {
        "id": 15,
        "name": "grass.png",
        "fullPath": "/grass.png",
        "key": "/grass.png",
        "width": 64,
        "height": 64,
        "frameWidth": 64,
        "frameHeight": 64,
        "frameMax": -1,
        "margin": 0,
        "spacing": 0,
        "anchorX": 0,
        "anchorY": 0,
        "fps": 10,
        "updated": 1409224247322,
        "atlas": ""
      },
      {
        "id": 16,
        "name": "ground.png",
        "fullPath": "/ground.png",
        "key": "/ground.png",
        "width": 64,
        "height": 64,
        "frameWidth": 64,
        "frameHeight": 64,
        "frameMax": -1,
        "margin": 0,
        "spacing": 0,
        "anchorX": 0,
        "anchorY": 0,
        "fps": 10,
        "updated": 1409224247323,
        "atlas": ""
      },
      {
        "id": 8,
        "name": "logo.png",
        "fullPath": "/logo.png",
        "key": "/logo.png",
        "width": 381,
        "height": 205,
        "frameWidth": 381,
        "frameHeight": 205,
        "frameMax": -1,
        "margin": 0,
        "spacing": 0,
        "anchorX": 0,
        "anchorY": 0,
        "fps": 10,
        "updated": 1409224185151,
        "atlas": ""
      },
      {
        "id": 17,
        "name": "rock.png",
        "fullPath": "/rock.png",
        "key": "/rock.png",
        "width": 64,
        "height": 64,
        "frameWidth": 64,
        "frameHeight": 64,
        "frameMax": -1,
        "margin": 0,
        "spacing": 0,
        "anchorX": 0,
        "anchorY": 0,
        "fps": 10,
        "updated": 1409224247323,
        "atlas": ""
      },
      {
        "id": 5,
        "name": "shop.png",
        "fullPath": "/shop.png",
        "key": "/shop.png",
        "width": 210,
        "height": 200,
        "frameWidth": 210,
        "frameHeight": 200,
        "frameMax": -1,
        "margin": 0,
        "spacing": 0,
        "anchorX": 0,
        "anchorY": 0,
        "fps": 10,
        "updated": 1409224103484,
        "atlas": ""
      },
      {
        "id": 9,
        "name": "sunburst_back.png",
        "fullPath": "/sunburst_back.png",
        "key": "/sunburst_back.png",
        "width": 539,
        "height": 545,
        "frameWidth": 539,
        "frameHeight": 545,
        "frameMax": -1,
        "margin": 0,
        "spacing": 0,
        "anchorX": 0,
        "anchorY": 0,
        "fps": 10,
        "updated": 1409224185153,
        "atlas": ""
      }
    ],
    "count": 24
  },
  "objects": {
    "name": "objects",
    "contents": [
      {
        "id": "tmp1406818026618",
        "name": "Loading",
        "x": 0,
        "y": 0,
        "angle": 0,
        "contents": [
          {
            "assetId": 1,
            "x": 256,
            "y": 192,
            "type": 0,
            "anchorX": 0,
            "anchorY": 0,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "alpha": 1,
            "frame": 0,
            "isVisible": 1,
            "isLocked": 0,
            "width": 190,
            "height": 9,
            "id": "tmp1406818026616",
            "name": "preload",
            "fullPath": "/Loading/preload",
            "contents": [],
            "assetKey": "/loading.png"
          },
          {
            "assetId": 2,
            "x": 256,
            "y": 192,
            "type": 0,
            "anchorX": 0,
            "anchorY": 0,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "alpha": 1,
            "frame": 0,
            "isVisible": 1,
            "isLocked": 0,
            "width": 190,
            "height": 9,
            "id": "tmp1406818026617",
            "name": "loading",
            "fullPath": "/Loading/loading",
            "contents": [],
            "assetKey": "/preload.png"
          }
        ],
        "isVisible": false,
        "isLocked": true,
        "isFixedToCamera": 0,
        "fullPath": "/Loading",
        "isClosed": true,
        "alpha": 1,
        "physics": {
          "enable": 0
        },
        "userData": {},
        "assetId": 19,
        "frame": 0,
        "scaleX": 1,
        "scaleY": 1,
        "width": 190,
        "height": 9,
        "movies": {
          "__main": {
            "frames": [],
            "info": {
              "fps": 60
            },
            "subdata": []
          }
        },
        "type": 1,
        "assetKey": "/background_city.png"
      },
      {
        "assetId": 7,
        "x": 134.52447552447555,
        "y": 209.0209790209791,
        "type": 0,
        "anchorX": 0.5,
        "anchorY": 0.5,
        "userData": {
          "gold": "0"
        },
        "physics": {
          "enable": 1,
          "immovable": 0,
          "bounce": {
            "x": 0,
            "y": 0
          },
          "gravity": {
            "allow": 1,
            "x": 0,
            "y": 1000
          },
          "size": {
            "width": 60,
            "height": 60,
            "offsetX": 0,
            "offsetY": 0
          },
          "rotation": {
            "allowRotation": 0,
            "maxAngular": 0
          },
          "maxVelocity": 0,
          "mass": 1,
          "collideWorldBounds": 1
        },
        "scaleX": 1,
        "scaleY": 1,
        "angle": 0,
        "alpha": 1,
        "frame": 0,
        "isVisible": 1,
        "isLocked": 0,
        "width": 90,
        "height": 90,
        "id": "tmp1411237186963",
        "name": "character",
        "fullPath": "/character",
        "movies": {
          "__main": {
            "frames": [],
            "info": {
              "fps": 60
            },
            "subdata": []
          }
        },
        "contents": [],
        "assetKey": "/character.png"
      },
      {
        "assetId": 5,
        "x": 420.86363636363643,
        "y": 122.41666666666663,
        "type": 0,
        "anchorX": 0,
        "anchorY": 0,
        "scaleX": 1,
        "scaleY": 1,
        "angle": 0,
        "alpha": 1,
        "frame": 0,
        "isVisible": true,
        "isLocked": 0,
        "width": 210,
        "height": 200,
        "id": "tmp1409238338815",
        "name": "shop",
        "fullPath": "/shop",
        "physics": {
          "enable": 0,
          "immovable": 0,
          "bounce": {
            "x": 1,
            "y": 1
          },
          "gravity": {
            "allow": 1,
            "x": 0,
            "y": 1000
          },
          "size": {
            "width": -1,
            "height": -1,
            "offsetX": 0,
            "offsetY": 0
          },
          "rotation": {
            "allowRotation": 1,
            "maxAngular": 0
          },
          "maxVelocity": 0,
          "mass": 1,
          "collideWorldBounds": 0
        },
        "userData": {},
        "movies": {
          "__main": {
            "frames": [],
            "info": {
              "fps": 60
            },
            "subdata": []
          }
        },
        "contents": [],
        "assetKey": "/shop.png"
      },
      {
        "x": 602.75,
        "y": 16.5,
        "type": 2,
        "anchorX": 0,
        "anchorY": 0,
        "scaleX": 1,
        "scaleY": 1,
        "angle": 0,
        "alpha": 1,
        "isVisible": true,
        "isLocked": 0,
        "text": "0",
        "id": "tmp1410851560073",
        "name": "points",
        "fullPath": "/points",
        "style": {
          "font": " 32px 'Arial'",
          "fill": "#000000",
          "align": "left",
          "stroke": "black",
          "strokeThickness": 0,
          "shadowOffsetX": 0,
          "shadowOffsetY": 0,
          "shadowColor": "rgba(0,0,0,0)",
          "shadowBlur": 0,
          "wordWrap": false,
          "wordWrapWidth": 100
        },
        "width": 14,
        "height": 31,
        "physics": {
          "enable": 0
        },
        "userData": {},
        "shadow": {},
        "movies": {
          "__main": {
            "frames": [],
            "info": {
              "fps": 60
            },
            "subdata": []
          }
        }
      },
      {
        "id": "tmp1409224160018",
        "name": "blocks",
        "x": 97.99999999999997,
        "y": -247.6666666666667,
        "angle": 0,
        "contents": [
          {
            "assetId": 16,
            "x": 97.00000000000001,
            "y": 630.6666666666665,
            "type": 0,
            "anchorX": 0,
            "anchorY": 0,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "alpha": 1,
            "isVisible": 1,
            "isLocked": 0,
            "width": 64,
            "height": 64,
            "id": "tmp1409224160017",
            "name": "ground28",
            "fullPath": "/blocks/ground28",
            "physics": {
              "enable": 0
            },
            "userData": {},
            "contents": [],
            "assetKey": "/ground.png"
          },
          {
            "assetId": 17,
            "x": 417,
            "y": 566.6666666666665,
            "type": 0,
            "anchorX": 0,
            "anchorY": 0,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "alpha": 1,
            "isVisible": 1,
            "isLocked": 0,
            "width": 64,
            "height": 64,
            "id": "tmp1409224159966",
            "name": "rock2",
            "fullPath": "/blocks/rock2",
            "physics": {
              "enable": 0
            },
            "userData": {},
            "contents": [],
            "assetKey": "/rock.png"
          },
          {
            "assetId": 17,
            "x": 289,
            "y": 566.6666666666665,
            "type": 0,
            "anchorX": 0,
            "anchorY": 0,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "alpha": 1,
            "isVisible": 1,
            "isLocked": 0,
            "width": 64,
            "height": 64,
            "id": "tmp1409224159964",
            "name": "rock",
            "fullPath": "/blocks/rock",
            "physics": {
              "enable": 0
            },
            "userData": {},
            "contents": [],
            "assetKey": "/rock.png"
          },
          {
            "assetId": 16,
            "x": 225,
            "y": 630.6666666666665,
            "type": 0,
            "anchorX": 0,
            "anchorY": 0,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "alpha": 1,
            "isVisible": 1,
            "isLocked": 0,
            "width": 64,
            "height": 64,
            "id": "tmp1409224160015",
            "name": "ground26",
            "fullPath": "/blocks/ground26",
            "physics": {
              "enable": 0
            },
            "userData": {},
            "contents": [],
            "assetKey": "/ground.png"
          },
          {
            "assetId": 16,
            "x": 225,
            "y": 694.6666666666665,
            "type": 0,
            "anchorX": 0,
            "anchorY": 0,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "alpha": 1,
            "isVisible": 1,
            "isLocked": 0,
            "width": 64,
            "height": 64,
            "id": "tmp1409224160014",
            "name": "ground25",
            "fullPath": "/blocks/ground25",
            "physics": {
              "enable": 0
            },
            "userData": {},
            "contents": [],
            "assetKey": "/ground.png"
          },
          {
            "assetId": 16,
            "x": 161,
            "y": 694.6666666666665,
            "type": 0,
            "anchorX": 0,
            "anchorY": 0,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "alpha": 1,
            "isVisible": 1,
            "isLocked": 0,
            "width": 64,
            "height": 64,
            "id": "tmp1409224160013",
            "name": "ground24",
            "fullPath": "/blocks/ground24",
            "physics": {
              "enable": 0
            },
            "userData": {},
            "contents": [],
            "assetKey": "/ground.png"
          },
          {
            "assetId": 16,
            "x": 161,
            "y": 630.6666666666665,
            "type": 0,
            "anchorX": 0,
            "anchorY": 0,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "alpha": 1,
            "isVisible": 1,
            "isLocked": 0,
            "width": 64,
            "height": 64,
            "id": "tmp1409224160016",
            "name": "ground27",
            "fullPath": "/blocks/ground27",
            "physics": {
              "enable": 0
            },
            "userData": {},
            "contents": [],
            "assetKey": "/ground.png"
          },
          {
            "assetId": 16,
            "x": -94.99999999999999,
            "y": 822.6666666666666,
            "type": 0,
            "anchorX": 0,
            "anchorY": 0,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "alpha": 1,
            "isVisible": 1,
            "isLocked": 0,
            "width": 64,
            "height": 64,
            "id": "tmp1409224160003",
            "name": "ground17",
            "fullPath": "/blocks/ground17",
            "physics": {
              "enable": 0
            },
            "userData": {},
            "contents": [],
            "assetKey": "/ground.png"
          },
          {
            "assetId": 16,
            "x": 481,
            "y": 822.6666666666666,
            "type": 0,
            "anchorX": 0,
            "anchorY": 0,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "alpha": 1,
            "isVisible": 1,
            "isLocked": 0,
            "width": 64,
            "height": 64,
            "id": "tmp1409224160001",
            "name": "ground15",
            "fullPath": "/blocks/ground15",
            "physics": {
              "enable": 0
            },
            "userData": {},
            "contents": [],
            "assetKey": "/ground.png"
          },
          {
            "assetId": 16,
            "x": 481,
            "y": 694.6666666666665,
            "type": 0,
            "anchorX": 0,
            "anchorY": 0,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "alpha": 1,
            "isVisible": 1,
            "isLocked": 0,
            "width": 64,
            "height": 64,
            "id": "tmp1409224159999",
            "name": "ground13",
            "fullPath": "/blocks/ground13",
            "physics": {
              "enable": 0
            },
            "userData": {},
            "contents": [],
            "assetKey": "/ground.png"
          },
          {
            "assetId": 16,
            "x": 417,
            "y": 758.6666666666666,
            "type": 0,
            "anchorX": 0,
            "anchorY": 0,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "alpha": 1,
            "isVisible": 1,
            "isLocked": 0,
            "width": 64,
            "height": 64,
            "id": "tmp1409224159997",
            "name": "ground11",
            "fullPath": "/blocks/ground11",
            "physics": {
              "enable": 0
            },
            "userData": {},
            "contents": [],
            "assetKey": "/ground.png"
          },
          {
            "assetId": 16,
            "x": 353,
            "y": 822.6666666666666,
            "type": 0,
            "anchorX": 0,
            "anchorY": 0,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "alpha": 1,
            "isVisible": 1,
            "isLocked": 0,
            "width": 64,
            "height": 64,
            "id": "tmp1409224159995",
            "name": "ground9",
            "fullPath": "/blocks/ground9",
            "physics": {
              "enable": 0
            },
            "userData": {},
            "contents": [],
            "assetKey": "/ground.png"
          },
          {
            "assetId": 16,
            "x": 161,
            "y": 822.6666666666666,
            "type": 0,
            "anchorX": 0,
            "anchorY": 0,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "alpha": 1,
            "isVisible": 1,
            "isLocked": 0,
            "width": 64,
            "height": 64,
            "id": "tmp1409224159993",
            "name": "ground7",
            "fullPath": "/blocks/ground7",
            "physics": {
              "enable": 0
            },
            "userData": {},
            "contents": [],
            "assetKey": "/ground.png"
          },
          {
            "assetId": 16,
            "x": 97.00000000000001,
            "y": 758.6666666666666,
            "type": 0,
            "anchorX": 0,
            "anchorY": 0,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "alpha": 1,
            "isVisible": 1,
            "isLocked": 0,
            "width": 64,
            "height": 64,
            "id": "tmp1409224159991",
            "name": "ground5",
            "fullPath": "/blocks/ground5",
            "physics": {
              "enable": 0
            },
            "userData": {},
            "contents": [],
            "assetKey": "/ground.png"
          },
          {
            "assetId": 17,
            "x": -30.999999999999982,
            "y": 758.6666666666666,
            "type": 0,
            "anchorX": 0,
            "anchorY": 0,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "alpha": 1,
            "isVisible": 1,
            "isLocked": 0,
            "width": 64,
            "height": 64,
            "id": "tmp1409224159989",
            "name": "rock7",
            "fullPath": "/blocks/rock7",
            "physics": {
              "enable": 0
            },
            "userData": {},
            "contents": [],
            "assetKey": "/rock.png"
          },
          {
            "assetId": 17,
            "x": 289,
            "y": 758.6666666666666,
            "type": 0,
            "anchorX": 0,
            "anchorY": 0,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "alpha": 1,
            "isVisible": 1,
            "isLocked": 0,
            "width": 64,
            "height": 64,
            "id": "tmp1409224159987",
            "name": "rock5",
            "fullPath": "/blocks/rock5",
            "physics": {
              "enable": 0
            },
            "userData": {},
            "contents": [],
            "assetKey": "/rock.png"
          },
          {
            "assetId": 16,
            "x": 289,
            "y": 630.6666666666665,
            "type": 0,
            "anchorX": 0,
            "anchorY": 0,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "alpha": 1,
            "isVisible": 1,
            "isLocked": 0,
            "width": 64,
            "height": 64,
            "id": "tmp1409224159985",
            "name": "ground3",
            "fullPath": "/blocks/ground3",
            "physics": {
              "enable": 0
            },
            "userData": {},
            "contents": [],
            "assetKey": "/ground.png"
          },
          {
            "assetId": 16,
            "x": 353,
            "y": 694.6666666666665,
            "type": 0,
            "anchorX": 0,
            "anchorY": 0,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "alpha": 1,
            "isVisible": 1,
            "isLocked": 0,
            "width": 64,
            "height": 64,
            "id": "tmp1409224159983",
            "name": "ground1",
            "fullPath": "/blocks/ground1",
            "physics": {
              "enable": 0
            },
            "userData": {},
            "contents": [],
            "assetKey": "/ground.png"
          },
          {
            "assetId": 14,
            "x": 33.000000000000014,
            "y": 822.6666666666666,
            "type": 0,
            "anchorX": 0,
            "anchorY": 0,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "alpha": 1,
            "isVisible": 1,
            "isLocked": 0,
            "width": 64,
            "height": 64,
            "id": "tmp1409224159981",
            "name": "gold6",
            "fullPath": "/blocks/gold6",
            "physics": {
              "enable": 0
            },
            "userData": {},
            "contents": [],
            "assetKey": "/gold.png"
          },
          {
            "assetId": 14,
            "x": 480,
            "y": 630.6666666666665,
            "type": 0,
            "anchorX": 0,
            "anchorY": 0,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "alpha": 1,
            "isVisible": 1,
            "isLocked": 0,
            "width": 64,
            "height": 64,
            "id": "tmp1409224159979",
            "name": "gold4",
            "fullPath": "/blocks/gold4",
            "physics": {
              "enable": 0
            },
            "userData": {},
            "contents": [],
            "assetKey": "/gold.png"
          },
          {
            "assetId": 14,
            "x": 353,
            "y": 758.6666666666666,
            "type": 0,
            "anchorX": 0,
            "anchorY": 0,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "alpha": 1,
            "isVisible": 1,
            "isLocked": 0,
            "width": 64,
            "height": 64,
            "id": "tmp1409224159977",
            "name": "gold2",
            "fullPath": "/blocks/gold2",
            "physics": {
              "enable": 0
            },
            "userData": {},
            "contents": [],
            "assetKey": "/gold.png"
          },
          {
            "assetId": 14,
            "x": -30.999999999999982,
            "y": 694.6666666666665,
            "type": 0,
            "anchorX": 0,
            "anchorY": 0,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "alpha": 1,
            "isVisible": 1,
            "isLocked": 0,
            "width": 64,
            "height": 64,
            "id": "tmp1409224159975",
            "name": "gold",
            "fullPath": "/blocks/gold",
            "physics": {
              "enable": 0
            },
            "userData": {},
            "contents": [],
            "assetKey": "/gold.png"
          },
          {
            "assetId": 15,
            "x": -94.99999999999999,
            "y": 567.6666666666665,
            "type": 0,
            "anchorX": 0,
            "anchorY": 0,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "alpha": 1,
            "isVisible": 1,
            "isLocked": 0,
            "width": 64,
            "height": 64,
            "id": "tmp1409224159973",
            "name": "grass4",
            "fullPath": "/blocks/grass4",
            "physics": {
              "enable": 0
            },
            "userData": {},
            "contents": [],
            "assetKey": "/grass.png"
          },
          {
            "assetId": 15,
            "x": 161.4117647058825,
            "y": 567.0784313725486,
            "type": 0,
            "anchorX": 0,
            "anchorY": 0,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "alpha": 1,
            "isVisible": 1,
            "isLocked": 0,
            "width": 64,
            "height": 64,
            "id": "tmp1409224159969",
            "name": "grass",
            "fullPath": "/blocks/grass",
            "physics": {
              "enable": 0
            },
            "userData": {},
            "contents": [],
            "assetKey": "/grass.png"
          },
          {
            "assetId": 17,
            "x": 481,
            "y": 566.6666666666665,
            "type": 0,
            "anchorX": 0,
            "anchorY": 0,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "alpha": 1,
            "isVisible": 1,
            "isLocked": 0,
            "width": 64,
            "height": 64,
            "id": "tmp1409224159967",
            "name": "rock3",
            "fullPath": "/blocks/rock3",
            "physics": {
              "enable": 0
            },
            "userData": {},
            "contents": [],
            "assetKey": "/rock.png"
          },
          {
            "assetId": 16,
            "x": -30.999999999999982,
            "y": 630.6666666666665,
            "type": 0,
            "anchorX": 0,
            "anchorY": 0,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "alpha": 1,
            "isVisible": 1,
            "isLocked": 0,
            "width": 64,
            "height": 64,
            "id": "tmp1409224160010",
            "name": "ground21",
            "fullPath": "/blocks/ground21",
            "physics": {
              "enable": 0
            },
            "userData": {},
            "contents": [],
            "assetKey": "/ground.png"
          },
          {
            "assetId": 17,
            "x": 33.000000000000014,
            "y": 758.6666666666666,
            "type": 0,
            "anchorX": 0,
            "anchorY": 0,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "alpha": 1,
            "isVisible": 1,
            "isLocked": 0,
            "width": 64,
            "height": 64,
            "id": "tmp1409224159990",
            "name": "rock8",
            "fullPath": "/blocks/rock8",
            "physics": {
              "enable": 0
            },
            "userData": {},
            "contents": [],
            "assetKey": "/rock.png"
          },
          {
            "assetId": 17,
            "x": 353,
            "y": 566.6666666666665,
            "type": 0,
            "anchorX": 0,
            "anchorY": 0,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "alpha": 1,
            "isVisible": 1,
            "isLocked": 0,
            "width": 64,
            "height": 64,
            "id": "tmp1409224159965",
            "name": "rock1",
            "fullPath": "/blocks/rock1",
            "physics": {
              "enable": 0
            },
            "userData": {},
            "contents": [],
            "assetKey": "/rock.png"
          },
          {
            "assetId": 16,
            "x": -30.999999999999982,
            "y": 822.6666666666666,
            "type": 0,
            "anchorX": 0,
            "anchorY": 0,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "alpha": 1,
            "isVisible": 1,
            "isLocked": 0,
            "width": 64,
            "height": 64,
            "id": "tmp1409224160002",
            "name": "ground16",
            "fullPath": "/blocks/ground16",
            "physics": {
              "enable": 0
            },
            "userData": {},
            "contents": [],
            "assetKey": "/ground.png"
          },
          {
            "assetId": 17,
            "x": 289,
            "y": 822.6666666666666,
            "type": 0,
            "anchorX": 0,
            "anchorY": 0,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "alpha": 1,
            "isVisible": 1,
            "isLocked": 0,
            "width": 64,
            "height": 64,
            "id": "tmp1409224159988",
            "name": "rock6",
            "fullPath": "/blocks/rock6",
            "physics": {
              "enable": 0
            },
            "userData": {},
            "contents": [],
            "assetKey": "/rock.png"
          },
          {
            "assetId": 16,
            "x": -94.99999999999999,
            "y": 630.6666666666665,
            "type": 0,
            "anchorX": 0,
            "anchorY": 0,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "alpha": 1,
            "isVisible": 1,
            "isLocked": 0,
            "width": 64,
            "height": 64,
            "id": "tmp1409224160009",
            "name": "ground20",
            "fullPath": "/blocks/ground20",
            "physics": {
              "enable": 0
            },
            "userData": {},
            "contents": [],
            "assetKey": "/ground.png"
          },
          {
            "assetId": 16,
            "x": 289,
            "y": 694.6666666666665,
            "type": 0,
            "anchorX": 0,
            "anchorY": 0,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "alpha": 1,
            "isVisible": 1,
            "isLocked": 0,
            "width": 64,
            "height": 64,
            "id": "tmp1409224159986",
            "name": "ground4",
            "fullPath": "/blocks/ground4",
            "physics": {
              "enable": 0
            },
            "userData": {},
            "contents": [],
            "assetKey": "/ground.png"
          },
          {
            "assetId": 16,
            "x": 481,
            "y": 758.6666666666666,
            "type": 0,
            "anchorX": 0,
            "anchorY": 0,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "alpha": 1,
            "isVisible": 1,
            "isLocked": 0,
            "width": 64,
            "height": 64,
            "id": "tmp1409224160000",
            "name": "ground14",
            "fullPath": "/blocks/ground14",
            "physics": {
              "enable": 0
            },
            "userData": {},
            "contents": [],
            "assetKey": "/ground.png"
          },
          {
            "assetId": 16,
            "x": 353,
            "y": 630.6666666666665,
            "type": 0,
            "anchorX": 0,
            "anchorY": 0,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "alpha": 1,
            "isVisible": 1,
            "isLocked": 0,
            "width": 64,
            "height": 64,
            "id": "tmp1409224159984",
            "name": "ground2",
            "fullPath": "/blocks/ground2",
            "physics": {
              "enable": 0
            },
            "userData": {},
            "contents": [],
            "assetKey": "/ground.png"
          },
          {
            "assetId": 16,
            "x": -94.99999999999999,
            "y": 694.6666666666665,
            "type": 0,
            "anchorX": 0,
            "anchorY": 0,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "alpha": 1,
            "isVisible": 1,
            "isLocked": 0,
            "width": 64,
            "height": 64,
            "id": "tmp1409224160008",
            "name": "ground19",
            "fullPath": "/blocks/ground19",
            "physics": {
              "enable": 0
            },
            "userData": {},
            "contents": [],
            "assetKey": "/ground.png"
          },
          {
            "assetId": 16,
            "x": 417,
            "y": 630.6666666666665,
            "type": 0,
            "anchorX": 0,
            "anchorY": 0,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "alpha": 1,
            "isVisible": 1,
            "isLocked": 0,
            "width": 64,
            "height": 64,
            "id": "tmp1409224159982",
            "name": "ground",
            "fullPath": "/blocks/ground",
            "physics": {
              "enable": 0
            },
            "userData": {},
            "contents": [],
            "assetKey": "/ground.png"
          },
          {
            "assetId": 16,
            "x": 417,
            "y": 694.6666666666665,
            "type": 0,
            "anchorX": 0,
            "anchorY": 0,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "alpha": 1,
            "isVisible": 1,
            "isLocked": 0,
            "width": 64,
            "height": 64,
            "id": "tmp1409224159998",
            "name": "ground12",
            "fullPath": "/blocks/ground12",
            "physics": {
              "enable": 0
            },
            "userData": {},
            "contents": [],
            "assetKey": "/ground.png"
          },
          {
            "assetId": 16,
            "x": 97.00000000000001,
            "y": 694.6666666666665,
            "type": 0,
            "anchorX": 0,
            "anchorY": 0,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "alpha": 1,
            "isVisible": 1,
            "isLocked": 0,
            "width": 64,
            "height": 64,
            "id": "tmp1409224160012",
            "name": "ground23",
            "fullPath": "/blocks/ground23",
            "physics": {
              "enable": 0
            },
            "userData": {},
            "contents": [],
            "assetKey": "/ground.png"
          },
          {
            "assetId": 14,
            "x": 161,
            "y": 758.6666666666666,
            "type": 0,
            "anchorX": 0,
            "anchorY": 0,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "alpha": 1,
            "isVisible": 1,
            "isLocked": 0,
            "width": 64,
            "height": 64,
            "id": "tmp1409224159980",
            "name": "gold5",
            "fullPath": "/blocks/gold5",
            "physics": {
              "enable": 0
            },
            "userData": {},
            "contents": [],
            "assetKey": "/gold.png"
          },
          {
            "assetId": 16,
            "x": 417,
            "y": 822.6666666666666,
            "type": 0,
            "anchorX": 0,
            "anchorY": 0,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "alpha": 1,
            "isVisible": 1,
            "isLocked": 0,
            "width": 64,
            "height": 64,
            "id": "tmp1409224159996",
            "name": "ground10",
            "fullPath": "/blocks/ground10",
            "physics": {
              "enable": 0
            },
            "userData": {},
            "contents": [],
            "assetKey": "/ground.png"
          },
          {
            "assetId": 14,
            "x": 225,
            "y": 758.6666666666666,
            "type": 0,
            "anchorX": 0,
            "anchorY": 0,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "alpha": 1,
            "isVisible": 1,
            "isLocked": 0,
            "width": 64,
            "height": 64,
            "id": "tmp1409224159978",
            "name": "gold3",
            "fullPath": "/blocks/gold3",
            "physics": {
              "enable": 0
            },
            "userData": {},
            "contents": [],
            "assetKey": "/gold.png"
          },
          {
            "assetId": 14,
            "x": 33.000000000000014,
            "y": 630.6666666666665,
            "type": 0,
            "anchorX": 0,
            "anchorY": 0,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "alpha": 1,
            "isVisible": 1,
            "isLocked": 0,
            "width": 64,
            "height": 64,
            "id": "tmp1409224159976",
            "name": "gold1",
            "fullPath": "/blocks/gold1",
            "physics": {
              "enable": 0
            },
            "userData": {},
            "contents": [],
            "assetKey": "/gold.png"
          },
          {
            "assetId": 16,
            "x": 33.000000000000014,
            "y": 694.6666666666665,
            "type": 0,
            "anchorX": 0,
            "anchorY": 0,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "alpha": 1,
            "isVisible": 1,
            "isLocked": 0,
            "width": 64,
            "height": 64,
            "id": "tmp1409224160011",
            "name": "ground22",
            "fullPath": "/blocks/ground22",
            "physics": {
              "enable": 0
            },
            "userData": {},
            "contents": [],
            "assetKey": "/ground.png"
          },
          {
            "assetId": 15,
            "x": -30.999999999999982,
            "y": 567.6666666666665,
            "type": 0,
            "anchorX": 0,
            "anchorY": 0,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "alpha": 1,
            "isVisible": 1,
            "isLocked": 0,
            "width": 64,
            "height": 64,
            "id": "tmp1409224159974",
            "name": "grass5",
            "fullPath": "/blocks/grass5",
            "physics": {
              "enable": 0
            },
            "userData": {},
            "contents": [],
            "assetKey": "/grass.png"
          },
          {
            "assetId": 15,
            "x": 33.000000000000014,
            "y": 567.6666666666665,
            "type": 0,
            "anchorX": 0,
            "anchorY": 0,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "alpha": 1,
            "isVisible": 1,
            "isLocked": 0,
            "width": 64,
            "height": 64,
            "id": "tmp1409224159972",
            "name": "grass3",
            "fullPath": "/blocks/grass3",
            "physics": {
              "enable": 0
            },
            "userData": {},
            "contents": [],
            "assetKey": "/grass.png"
          },
          {
            "assetId": 16,
            "x": 225,
            "y": 822.6666666666666,
            "type": 0,
            "anchorX": 0,
            "anchorY": 0,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "alpha": 1,
            "isVisible": 1,
            "isLocked": 0,
            "width": 64,
            "height": 64,
            "id": "tmp1409224159994",
            "name": "ground8",
            "fullPath": "/blocks/ground8",
            "physics": {
              "enable": 0
            },
            "userData": {},
            "contents": [],
            "assetKey": "/ground.png"
          },
          {
            "assetId": 16,
            "x": -94.99999999999999,
            "y": 758.6666666666666,
            "type": 0,
            "anchorX": 0,
            "anchorY": 0,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "alpha": 1,
            "isVisible": 1,
            "isLocked": 0,
            "width": 64,
            "height": 64,
            "id": "tmp1409224160007",
            "name": "ground18",
            "fullPath": "/blocks/ground18",
            "physics": {
              "enable": 0
            },
            "userData": {},
            "contents": [],
            "assetKey": "/ground.png"
          },
          {
            "assetId": 15,
            "x": 98.31138975966559,
            "y": 566.9885057471257,
            "type": 0,
            "anchorX": 0,
            "anchorY": 0,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "alpha": 1,
            "isVisible": 1,
            "isLocked": 0,
            "width": 64,
            "height": 64,
            "id": "tmp1409224159970",
            "name": "grass1",
            "fullPath": "/blocks/grass1",
            "physics": {
              "enable": 0
            },
            "userData": {},
            "contents": [],
            "assetKey": "/grass.png"
          },
          {
            "assetId": 16,
            "x": 97.00000000000001,
            "y": 822.6666666666666,
            "type": 0,
            "anchorX": 0,
            "anchorY": 0,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "alpha": 1,
            "isVisible": 1,
            "isLocked": 0,
            "width": 64,
            "height": 64,
            "id": "tmp1409224159992",
            "name": "ground6",
            "fullPath": "/blocks/ground6",
            "physics": {
              "enable": 0
            },
            "userData": {},
            "contents": [],
            "assetKey": "/ground.png"
          },
          {
            "assetId": 17,
            "x": 225,
            "y": 566.6666666666665,
            "type": 0,
            "anchorX": 0,
            "anchorY": 0,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "alpha": 1,
            "isVisible": 1,
            "isLocked": 0,
            "width": 64,
            "height": 64,
            "id": "tmp1409224159968",
            "name": "rock4",
            "fullPath": "/blocks/rock4",
            "physics": {
              "enable": 0
            },
            "userData": {},
            "contents": [],
            "assetKey": "/rock.png"
          }
        ],
        "isVisible": true,
        "isLocked": 0,
        "fullPath": "/blocks",
        "isClosed": true,
        "alpha": 1,
        "scaleX": 1,
        "scaleY": 1,
        "width": 640,
        "height": 320.0000000000001,
        "physics": {
          "enable": 1,
          "immovable": 1,
          "bounce": {
            "x": 1,
            "y": 1
          },
          "gravity": {
            "allow": 1,
            "x": 0,
            "y": 0
          },
          "size": {
            "width": -1,
            "height": -1,
            "offsetX": 0,
            "offsetY": 0
          },
          "rotation": {
            "allowRotation": 0,
            "maxAngular": 0
          },
          "maxVelocity": 0,
          "mass": 1,
          "collideWorldBounds": 0
        },
        "userData": {},
        "movies": {
          "__main": {
            "frames": [],
            "info": {
              "fps": 60
            },
            "subdata": []
          }
        },
        "type": 1
      },
      {
        "id": "tmp1409238338817",
        "name": "bg",
        "x": -11.285714285714285,
        "y": 31.714285714285694,
        "angle": 0,
        "contents": [
          {
            "assetId": 20,
            "x": 9.519230769230916,
            "y": 243.10897435897465,
            "type": 0,
            "anchorX": 0,
            "anchorY": 0,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "alpha": 1,
            "frame": 0,
            "isVisible": 1,
            "isLocked": 0,
            "width": 640,
            "height": 47,
            "id": "tmp1409224159963",
            "name": "background_grass",
            "fullPath": "/bg/background_grass",
            "physics": {
              "enable": 0
            },
            "userData": {},
            "contents": [],
            "assetKey": "/background_grass.png"
          },
          {
            "assetId": 24,
            "x": 12.661421911421707,
            "y": 201.88694638694622,
            "type": 0,
            "anchorX": 0,
            "anchorY": 0,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "alpha": 1,
            "frame": 0,
            "isVisible": 1,
            "isLocked": 0,
            "width": 640,
            "height": 85,
            "id": "tmp1409224159962",
            "name": "background_hill1",
            "fullPath": "/bg/background_hill1",
            "physics": {
              "enable": 0
            },
            "userData": {},
            "contents": [],
            "assetKey": "/background_hill1.png"
          },
          {
            "assetId": 22,
            "x": 15.159090909090981,
            "y": 149.46212121212113,
            "type": 0,
            "anchorX": 0,
            "anchorY": 0,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "alpha": 1,
            "frame": 0,
            "isVisible": 1,
            "isLocked": 0,
            "width": 640,
            "height": 99,
            "id": "tmp1409224159961",
            "name": "background_hill2",
            "fullPath": "/bg/background_hill2",
            "physics": {
              "enable": 0
            },
            "userData": {},
            "contents": [],
            "assetKey": "/background_hill2.png"
          },
          {
            "assetId": 19,
            "x": 10.641025641025543,
            "y": 62.461538461538446,
            "type": 0,
            "anchorX": 0,
            "anchorY": 0,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "alpha": 1,
            "frame": 0,
            "isVisible": 1,
            "isLocked": 0,
            "width": 640,
            "height": 188,
            "id": "tmp1409224159960",
            "name": "background_city",
            "fullPath": "/bg/background_city",
            "physics": {
              "enable": 0
            },
            "userData": {},
            "contents": [],
            "assetKey": "/background_city.png"
          },
          {
            "assetId": 23,
            "x": 10.923076923076936,
            "y": -30.76923076923079,
            "type": 0,
            "anchorX": 0,
            "anchorY": 0,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "alpha": 1,
            "frame": 0,
            "isVisible": 1,
            "isLocked": 0,
            "width": 640,
            "height": 320,
            "id": "tmp1409224159959",
            "name": "background_sky",
            "fullPath": "/bg/background_sky",
            "physics": {
              "enable": 0
            },
            "userData": {},
            "contents": [],
            "assetKey": "/background_sky.png"
          }
        ],
        "isVisible": true,
        "isLocked": 0,
        "fullPath": "/bg",
        "isClosed": true,
        "alpha": 1,
        "physics": {
          "enable": 0
        },
        "userData": {},
        "scaleX": 1,
        "scaleY": 1,
        "width": 897,
        "height": 800,
        "isFixedToCamera": 0,
        "movies": {
          "__main": {
            "frames": [],
            "info": {
              "fps": 60
            },
            "subdata": []
          }
        },
        "type": 1
      }
    ],
    "count": 0
  },
  "map": {
    "cameraX": -475,
    "cameraY": -16,
    "worldWidth": 640,
    "worldHeight": 640,
    "viewportWidth": 640,
    "viewportHeight": 640,
    "gridX": 64,
    "gridY": 64,
    "gridOffsetX": 0,
    "gridOffsetY": 0,
    "showGrid": 1,
    "gridOpacity": 0.3,
    "backgroundColor": "#222222",
    "movieInfo": {
      "fps": 60,
      "lastFrame": 60
    },
    "physics": {
      "enable": 0
    }
  }
};
